### ISSUE TITLE
Address Node Module Security Issues

### ISSUE THREAD

**Issue by twcwennik** [TheWeatherCompany/maps-pangea-portal#35]
We saw these warnings when running npm, and now github is also flagging them. Please find alternative modules or make updates so they are no longer required.

<img width="1202" alt="portal_security_issues" src="https://user-images.githubusercontent.com/8309920/57616740-e74c1c80-754c-11e9-999f-5212f9960b01.png">

**Comment by eliotj** [comment]
Issue was caused by some unnecessary npm packages. Removed and pushed new package.json and package-lock.json to master.
